# Runs content type publishing jobs
Write-Host Running CT Publishing Timer Job... 
Get-SPTimerJob MetadataHubTimerJob | Start-SPTimerJob
Write-Host Running CT Subscriber Timer Job... 
Get-SPTimerJob MetadataSubscriberTimerJob | Start-SPTimerJob